// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCaching.Data;

#nullable disable

namespace ProductCaching.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030151447_DBInit")]
    partial class DBInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductCaching.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sản phẩm cao cấp số 1",
                            Name = "Điện thoại Apple 1",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sản phẩm cao cấp số 2",
                            Name = "Tai nghe Samsung 2",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sản phẩm cao cấp số 3",
                            Name = "Màn hình Sony 3",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sản phẩm cao cấp số 4",
                            Name = "Bàn phím LG 4",
                            Price = 600000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sản phẩm cao cấp số 5",
                            Name = "Chuột Asus 5",
                            Price = 750000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sản phẩm cao cấp số 6",
                            Name = "Webcam Logitech 6",
                            Price = 900000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sản phẩm cao cấp số 7",
                            Name = "Loa HP 7",
                            Price = 1050000m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sản phẩm cao cấp số 8",
                            Name = "Router Acer 8",
                            Price = 1200000m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sản phẩm cao cấp số 9",
                            Name = "USB Lenovo 9",
                            Price = 1350000m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sản phẩm cao cấp số 10",
                            Name = "Laptop Dell 10",
                            Price = 1000000m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Sản phẩm cao cấp số 11",
                            Name = "Điện thoại Apple 11",
                            Price = 1150000m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Sản phẩm cao cấp số 12",
                            Name = "Tai nghe Samsung 12",
                            Price = 1300000m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Sản phẩm cao cấp số 13",
                            Name = "Màn hình Sony 13",
                            Price = 1450000m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sản phẩm cao cấp số 14",
                            Name = "Bàn phím LG 14",
                            Price = 1600000m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Sản phẩm cao cấp số 15",
                            Name = "Chuột Asus 15",
                            Price = 1750000m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Sản phẩm cao cấp số 16",
                            Name = "Webcam Logitech 16",
                            Price = 1900000m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Sản phẩm cao cấp số 17",
                            Name = "Loa HP 17",
                            Price = 2050000m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Sản phẩm cao cấp số 18",
                            Name = "Router Acer 18",
                            Price = 2200000m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Sản phẩm cao cấp số 19",
                            Name = "USB Lenovo 19",
                            Price = 2350000m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Sản phẩm cao cấp số 20",
                            Name = "Laptop Dell 20",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Sản phẩm cao cấp số 21",
                            Name = "Điện thoại Apple 21",
                            Price = 2150000m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Sản phẩm cao cấp số 22",
                            Name = "Tai nghe Samsung 22",
                            Price = 2300000m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Sản phẩm cao cấp số 23",
                            Name = "Màn hình Sony 23",
                            Price = 2450000m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Sản phẩm cao cấp số 24",
                            Name = "Bàn phím LG 24",
                            Price = 2600000m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Sản phẩm cao cấp số 25",
                            Name = "Chuột Asus 25",
                            Price = 2750000m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Sản phẩm cao cấp số 26",
                            Name = "Webcam Logitech 26",
                            Price = 2900000m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Sản phẩm cao cấp số 27",
                            Name = "Loa HP 27",
                            Price = 3050000m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Sản phẩm cao cấp số 28",
                            Name = "Router Acer 28",
                            Price = 3200000m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Sản phẩm cao cấp số 29",
                            Name = "USB Lenovo 29",
                            Price = 3350000m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Sản phẩm cao cấp số 30",
                            Name = "Laptop Dell 30",
                            Price = 3000000m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Sản phẩm cao cấp số 31",
                            Name = "Điện thoại Apple 31",
                            Price = 3150000m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Sản phẩm cao cấp số 32",
                            Name = "Tai nghe Samsung 32",
                            Price = 3300000m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Sản phẩm cao cấp số 33",
                            Name = "Màn hình Sony 33",
                            Price = 3450000m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Sản phẩm cao cấp số 34",
                            Name = "Bàn phím LG 34",
                            Price = 3600000m
                        },
                        new
                        {
                            Id = 35,
                            Description = "Sản phẩm cao cấp số 35",
                            Name = "Chuột Asus 35",
                            Price = 3750000m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Sản phẩm cao cấp số 36",
                            Name = "Webcam Logitech 36",
                            Price = 3900000m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Sản phẩm cao cấp số 37",
                            Name = "Loa HP 37",
                            Price = 4050000m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Sản phẩm cao cấp số 38",
                            Name = "Router Acer 38",
                            Price = 4200000m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Sản phẩm cao cấp số 39",
                            Name = "USB Lenovo 39",
                            Price = 4350000m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Sản phẩm cao cấp số 40",
                            Name = "Laptop Dell 40",
                            Price = 4000000m
                        },
                        new
                        {
                            Id = 41,
                            Description = "Sản phẩm cao cấp số 41",
                            Name = "Điện thoại Apple 41",
                            Price = 4150000m
                        },
                        new
                        {
                            Id = 42,
                            Description = "Sản phẩm cao cấp số 42",
                            Name = "Tai nghe Samsung 42",
                            Price = 4300000m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Sản phẩm cao cấp số 43",
                            Name = "Màn hình Sony 43",
                            Price = 4450000m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Sản phẩm cao cấp số 44",
                            Name = "Bàn phím LG 44",
                            Price = 4600000m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Sản phẩm cao cấp số 45",
                            Name = "Chuột Asus 45",
                            Price = 4750000m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Sản phẩm cao cấp số 46",
                            Name = "Webcam Logitech 46",
                            Price = 4900000m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Sản phẩm cao cấp số 47",
                            Name = "Loa HP 47",
                            Price = 5050000m
                        },
                        new
                        {
                            Id = 48,
                            Description = "Sản phẩm cao cấp số 48",
                            Name = "Router Acer 48",
                            Price = 5200000m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Sản phẩm cao cấp số 49",
                            Name = "USB Lenovo 49",
                            Price = 5350000m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Sản phẩm cao cấp số 50",
                            Name = "Laptop Dell 50",
                            Price = 5000000m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Sản phẩm cao cấp số 51",
                            Name = "Điện thoại Apple 51",
                            Price = 5150000m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Sản phẩm cao cấp số 52",
                            Name = "Tai nghe Samsung 52",
                            Price = 5300000m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Sản phẩm cao cấp số 53",
                            Name = "Màn hình Sony 53",
                            Price = 5450000m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Sản phẩm cao cấp số 54",
                            Name = "Bàn phím LG 54",
                            Price = 5600000m
                        },
                        new
                        {
                            Id = 55,
                            Description = "Sản phẩm cao cấp số 55",
                            Name = "Chuột Asus 55",
                            Price = 5750000m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Sản phẩm cao cấp số 56",
                            Name = "Webcam Logitech 56",
                            Price = 5900000m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Sản phẩm cao cấp số 57",
                            Name = "Loa HP 57",
                            Price = 6050000m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Sản phẩm cao cấp số 58",
                            Name = "Router Acer 58",
                            Price = 6200000m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Sản phẩm cao cấp số 59",
                            Name = "USB Lenovo 59",
                            Price = 6350000m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Sản phẩm cao cấp số 60",
                            Name = "Laptop Dell 60",
                            Price = 6000000m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Sản phẩm cao cấp số 61",
                            Name = "Điện thoại Apple 61",
                            Price = 6150000m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Sản phẩm cao cấp số 62",
                            Name = "Tai nghe Samsung 62",
                            Price = 6300000m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Sản phẩm cao cấp số 63",
                            Name = "Màn hình Sony 63",
                            Price = 6450000m
                        },
                        new
                        {
                            Id = 64,
                            Description = "Sản phẩm cao cấp số 64",
                            Name = "Bàn phím LG 64",
                            Price = 6600000m
                        },
                        new
                        {
                            Id = 65,
                            Description = "Sản phẩm cao cấp số 65",
                            Name = "Chuột Asus 65",
                            Price = 6750000m
                        },
                        new
                        {
                            Id = 66,
                            Description = "Sản phẩm cao cấp số 66",
                            Name = "Webcam Logitech 66",
                            Price = 6900000m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Sản phẩm cao cấp số 67",
                            Name = "Loa HP 67",
                            Price = 7050000m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Sản phẩm cao cấp số 68",
                            Name = "Router Acer 68",
                            Price = 7200000m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Sản phẩm cao cấp số 69",
                            Name = "USB Lenovo 69",
                            Price = 7350000m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Sản phẩm cao cấp số 70",
                            Name = "Laptop Dell 70",
                            Price = 7000000m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Sản phẩm cao cấp số 71",
                            Name = "Điện thoại Apple 71",
                            Price = 7150000m
                        },
                        new
                        {
                            Id = 72,
                            Description = "Sản phẩm cao cấp số 72",
                            Name = "Tai nghe Samsung 72",
                            Price = 7300000m
                        },
                        new
                        {
                            Id = 73,
                            Description = "Sản phẩm cao cấp số 73",
                            Name = "Màn hình Sony 73",
                            Price = 7450000m
                        },
                        new
                        {
                            Id = 74,
                            Description = "Sản phẩm cao cấp số 74",
                            Name = "Bàn phím LG 74",
                            Price = 7600000m
                        },
                        new
                        {
                            Id = 75,
                            Description = "Sản phẩm cao cấp số 75",
                            Name = "Chuột Asus 75",
                            Price = 7750000m
                        },
                        new
                        {
                            Id = 76,
                            Description = "Sản phẩm cao cấp số 76",
                            Name = "Webcam Logitech 76",
                            Price = 7900000m
                        },
                        new
                        {
                            Id = 77,
                            Description = "Sản phẩm cao cấp số 77",
                            Name = "Loa HP 77",
                            Price = 8050000m
                        },
                        new
                        {
                            Id = 78,
                            Description = "Sản phẩm cao cấp số 78",
                            Name = "Router Acer 78",
                            Price = 8200000m
                        },
                        new
                        {
                            Id = 79,
                            Description = "Sản phẩm cao cấp số 79",
                            Name = "USB Lenovo 79",
                            Price = 8350000m
                        },
                        new
                        {
                            Id = 80,
                            Description = "Sản phẩm cao cấp số 80",
                            Name = "Laptop Dell 80",
                            Price = 8000000m
                        },
                        new
                        {
                            Id = 81,
                            Description = "Sản phẩm cao cấp số 81",
                            Name = "Điện thoại Apple 81",
                            Price = 8150000m
                        },
                        new
                        {
                            Id = 82,
                            Description = "Sản phẩm cao cấp số 82",
                            Name = "Tai nghe Samsung 82",
                            Price = 8300000m
                        },
                        new
                        {
                            Id = 83,
                            Description = "Sản phẩm cao cấp số 83",
                            Name = "Màn hình Sony 83",
                            Price = 8450000m
                        },
                        new
                        {
                            Id = 84,
                            Description = "Sản phẩm cao cấp số 84",
                            Name = "Bàn phím LG 84",
                            Price = 8600000m
                        },
                        new
                        {
                            Id = 85,
                            Description = "Sản phẩm cao cấp số 85",
                            Name = "Chuột Asus 85",
                            Price = 8750000m
                        },
                        new
                        {
                            Id = 86,
                            Description = "Sản phẩm cao cấp số 86",
                            Name = "Webcam Logitech 86",
                            Price = 8900000m
                        },
                        new
                        {
                            Id = 87,
                            Description = "Sản phẩm cao cấp số 87",
                            Name = "Loa HP 87",
                            Price = 9050000m
                        },
                        new
                        {
                            Id = 88,
                            Description = "Sản phẩm cao cấp số 88",
                            Name = "Router Acer 88",
                            Price = 9200000m
                        },
                        new
                        {
                            Id = 89,
                            Description = "Sản phẩm cao cấp số 89",
                            Name = "USB Lenovo 89",
                            Price = 9350000m
                        },
                        new
                        {
                            Id = 90,
                            Description = "Sản phẩm cao cấp số 90",
                            Name = "Laptop Dell 90",
                            Price = 9000000m
                        },
                        new
                        {
                            Id = 91,
                            Description = "Sản phẩm cao cấp số 91",
                            Name = "Điện thoại Apple 91",
                            Price = 9150000m
                        },
                        new
                        {
                            Id = 92,
                            Description = "Sản phẩm cao cấp số 92",
                            Name = "Tai nghe Samsung 92",
                            Price = 9300000m
                        },
                        new
                        {
                            Id = 93,
                            Description = "Sản phẩm cao cấp số 93",
                            Name = "Màn hình Sony 93",
                            Price = 9450000m
                        },
                        new
                        {
                            Id = 94,
                            Description = "Sản phẩm cao cấp số 94",
                            Name = "Bàn phím LG 94",
                            Price = 9600000m
                        },
                        new
                        {
                            Id = 95,
                            Description = "Sản phẩm cao cấp số 95",
                            Name = "Chuột Asus 95",
                            Price = 9750000m
                        },
                        new
                        {
                            Id = 96,
                            Description = "Sản phẩm cao cấp số 96",
                            Name = "Webcam Logitech 96",
                            Price = 9900000m
                        },
                        new
                        {
                            Id = 97,
                            Description = "Sản phẩm cao cấp số 97",
                            Name = "Loa HP 97",
                            Price = 10050000m
                        },
                        new
                        {
                            Id = 98,
                            Description = "Sản phẩm cao cấp số 98",
                            Name = "Router Acer 98",
                            Price = 10200000m
                        },
                        new
                        {
                            Id = 99,
                            Description = "Sản phẩm cao cấp số 99",
                            Name = "USB Lenovo 99",
                            Price = 10350000m
                        },
                        new
                        {
                            Id = 100,
                            Description = "Sản phẩm cao cấp số 100",
                            Name = "Laptop Dell 100",
                            Price = 10000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
